const scienceResearchQuiz = [
  {
    que: "Which of the following is the most reliable method for establishing a causal relationship in scientific research?",
    opt1: "Observational Study",
    opt2: "Case Study",
    opt3: "Randomized Controlled Trial",
    opt4: "Survey Research",
    ans: 3,
  },
  {
    que: "What is the primary purpose of a peer review process in scientific research?",
    opt1: "To increase the visibility of research papers",
    opt2: "To ensure the quality and validity of research before publication",
    opt3: "To allow researchers to claim priority for discoveries",
    opt4: "To attract funding for future studies",
    ans: 2,
  },
  {
    que: "Which branch of science deals with the study of the fundamental particles and forces of nature?",
    opt1: "Biochemistry",
    opt2: "Quantum Physics",
    opt3: "Astronomy",
    opt4: "Molecular Biology",
    ans: 2,
  },
  {
    que: "What is the primary difference between basic research and applied research?",
    opt1: "Basic research focuses on commercial applications, while applied research explores fundamental principles.",
    opt2: "Basic research aims to expand knowledge without immediate application, while applied research seeks to solve practical problems.",
    opt3: "Basic research uses experimental methods, while applied research only uses theoretical models.",
    opt4: "Applied research is conducted only by private companies, while basic research is done by universities.",
    ans: 2,
  },
  {
    que: "Which of the following best defines the 'null hypothesis' in scientific research?",
    opt1: "A hypothesis that predicts a strong effect",
    opt2: "A hypothesis that there is no significant difference or relationship between variables",
    opt3: "A hypothesis that must always be proven true",
    opt4: "A hypothesis that is formulated after data collection",
    ans: 2,
  },
  {
    que: "What is the main advantage of using a double-blind experimental design in research?",
    opt1: "It allows researchers to manipulate results more easily.",
    opt2: "It prevents both participants and experimenters from being biased.",
    opt3: "It ensures that only the experimenters are aware of the research hypothesis.",
    opt4: "It increases the speed of data collection and analysis.",
    ans: 2,
  },
  {
    que: "Which scientific discovery led to the development of modern vaccines?",
    opt1: "The discovery of antibiotics",
    opt2: "The discovery of DNA structure",
    opt3: "The discovery of the immune system’s response to weakened pathogens",
    opt4: "The discovery of X-rays",
    ans: 3,
  },
  {
    que: "Which of the following is NOT a feature of a good scientific theory?",
    opt1: "It can be tested and falsified",
    opt2: "It explains existing observations and predicts new ones",
    opt3: "It can never be changed or modified",
    opt4: "It is based on empirical evidence",
    ans: 3,
  },
  {
    que: "Which statistical test is commonly used to compare the means of two independent groups?",
    opt1: "Chi-square test",
    opt2: "T-test",
    opt3: "ANOVA",
    opt4: "Regression analysis",
    ans: 2,
  },
  {
    que: "Which of the following best describes the difference between a scientific law and a scientific theory?",
    opt1: "A law is a detailed explanation, while a theory is a simple observation.",
    opt2: "A law describes a natural phenomenon, while a theory explains why it occurs.",
    opt3: "A law can change, while a theory remains constant.",
    opt4: "A theory must be mathematically proven to become a law.",
    ans: 2,
  },
];

const lawPublicAdministrationQuiz = [
  {
    que: "Which branch of government is responsible for interpreting laws in a democratic system?",
    opt1: "Executive",
    opt2: "Legislative",
    opt3: "Judicial",
    opt4: "Administrative",
    ans: 3,
  },
  {
    que: "What is the primary purpose of administrative law?",
    opt1: "To regulate private contracts",
    opt2: "To ensure fair procedures in government actions",
    opt3: "To create criminal laws",
    opt4: "To govern international relations",
    ans: 2,
  },
  {
    que: "Which legal principle ensures that no one is above the law, including government officials?",
    opt1: "Habeas Corpus",
    opt2: "Rule of Law",
    opt3: "Stare Decisis",
    opt4: "Ex Post Facto",
    ans: 2,
  },
  {
    que: "Which international organization is primarily responsible for maintaining international peace and security?",
    opt1: "World Trade Organization (WTO)",
    opt2: "United Nations Security Council (UNSC)",
    opt3: "International Monetary Fund (IMF)",
    opt4: "World Health Organization (WHO)",
    ans: 2,
  },
  {
    que: "What is the primary role of public administration?",
    opt1: "To create new laws",
    opt2: "To manage public policies and government operations",
    opt3: "To represent citizens in elections",
    opt4: "To determine constitutional validity of laws",
    ans: 2,
  },
  {
    que: "Which of the following is a key characteristic of a bureaucratic government system?",
    opt1: "Decentralized decision-making",
    opt2: "Strict hierarchy and formal rules",
    opt3: "Direct public participation in policymaking",
    opt4: "Complete privatization of services",
    ans: 2,
  },
  {
    que: "Which legal document serves as the supreme law of a country?",
    opt1: "Statutory Law",
    opt2: "Judicial Precedent",
    opt3: "Constitution",
    opt4: "Administrative Order",
    ans: 3,
  },
  {
    que: "What is the function of a 'writ of habeas corpus'?",
    opt1: "To challenge unlawful detention or imprisonment",
    opt2: "To overturn a judicial decision",
    opt3: "To demand a retrial in a higher court",
    opt4: "To enforce international treaties",
    ans: 1,
  },
  {
    que: "Which of the following is an example of a public policy?",
    opt1: "A company’s marketing strategy",
    opt2: "A government’s healthcare program",
    opt3: "A law firm's business model",
    opt4: "A local restaurant’s pricing policy",
    ans: 2,
  },
  {
    que: "Which legal system is based on precedent set by previous court rulings?",
    opt1: "Civil Law",
    opt2: "Common Law",
    opt3: "Religious Law",
    opt4: "Constitutional Law",
    ans: 2,
  },
];

const financeAccountingQuiz = [
  {
    que: "Which financial statement provides a snapshot of a company's financial position at a specific point in time?",
    opt1: "Income Statement",
    opt2: "Cash Flow Statement",
    opt3: "Balance Sheet",
    opt4: "Statement of Retained Earnings",
    ans: 3,
  },
  {
    que: "Which accounting principle requires companies to record expenses in the same period as the revenues they help generate?",
    opt1: "Conservatism Principle",
    opt2: "Matching Principle",
    opt3: "Revenue Recognition Principle",
    opt4: "Going Concern Principle",
    ans: 2,
  },
  {
    que: "Which of the following is NOT a component of the financial statements under GAAP?",
    opt1: "Statement of Financial Position",
    opt2: "Statement of Changes in Equity",
    opt3: "Market Valuation Report",
    opt4: "Statement of Comprehensive Income",
    ans: 3,
  },
  {
    que: "Which financial ratio is used to measure a company's ability to pay short-term liabilities with its most liquid assets?",
    opt1: "Current Ratio",
    opt2: "Debt-to-Equity Ratio",
    opt3: "Quick Ratio",
    opt4: "Return on Assets",
    ans: 3,
  },
  {
    que: "What is the main purpose of accrual accounting?",
    opt1: "To record transactions only when cash is exchanged",
    opt2: "To recognize revenues and expenses when they are incurred, regardless of cash flow",
    opt3: "To simplify bookkeeping by using cash-based transactions",
    opt4: "To avoid tax liabilities until payments are received",
    ans: 2,
  },
  {
    que: "Which type of financial analysis compares a company's financial data over multiple periods?",
    opt1: "Cross-sectional analysis",
    opt2: "Vertical analysis",
    opt3: "Time-series analysis",
    opt4: "Market capitalization analysis",
    ans: 3,
  },
  {
    que: "Which of the following financial instruments is considered the safest investment?",
    opt1: "Corporate Bonds",
    opt2: "Mutual Funds",
    opt3: "Government Treasury Bonds",
    opt4: "Common Stock",
    ans: 3,
  },
  {
    que: "What does EBITDA stand for in financial analysis?",
    opt1: "Earnings Before Interest, Taxes, Depreciation, and Amortization",
    opt2: "Earnings Before Inflation, Taxes, and Business Adjustments",
    opt3: "Equity-Based Interest, Taxes, and Balance Transactions",
    opt4: "Earnings Before Internal Transactions and Budget Allocation",
    ans: 1,
  },
  {
    que: "Which accounting concept assumes that a business will continue operating indefinitely?",
    opt1: "Materiality Principle",
    opt2: "Going Concern Assumption",
    opt3: "Consistency Principle",
    opt4: "Periodicity Assumption",
    ans: 2,
  },
  {
    que: "What is the primary purpose of financial leverage?",
    opt1: "To increase the return on equity by using borrowed funds",
    opt2: "To decrease operational risks",
    opt3: "To reduce financial obligations",
    opt4: "To increase cash reserves",
    ans: 1,
  },
];

const generalAptitudeQuiz = [
  {
    que: "A tank can be filled by two pipes A and B in 20 and 30 minutes respectively. A third pipe C can empty the tank in 15 minutes. If all three pipes are opened simultaneously, how long will it take to fill the tank?",
    opt1: "10 minutes",
    opt2: "20 minutes",
    opt3: "30 minutes",
    opt4: "The tank will never be filled",
    ans: 4,
  },
  {
    que: "In a certain code language, 'MANGO' is written as 'LZMFN'. How is 'APPLE' written in that code?",
    opt1: "ZOKKD",
    opt2: "ZOKKC",
    opt3: "ZOKKE",
    opt4: "ZOKKF",
    ans: 2,
  },
  {
    que: "A man invests ₹10,000 at an annual compound interest rate of 10%. What will be the amount after 2 years?",
    opt1: "₹12,100",
    opt2: "₹12,000",
    opt3: "₹11,000",
    opt4: "₹12,500",
    ans: 1,
  },
  {
    que: "If the sum of the ages of A and B is 50 years, and 5 years ago, the ratio of their ages was 3:2, what is the present age of A?",
    opt1: "30 years",
    opt2: "28 years",
    opt3: "32 years",
    opt4: "35 years",
    ans: 3,
  },
  {
    que: "A train 150 meters long is running at a speed of 60 km/h. How long will it take to pass a pole?",
    opt1: "9 seconds",
    opt2: "7.5 seconds",
    opt3: "12 seconds",
    opt4: "15 seconds",
    ans: 2,
  },
  {
    que: "If the probability of an event occurring is 0.7, what is the probability of the event not occurring?",
    opt1: "0.3",
    opt2: "0.7",
    opt3: "0.5",
    opt4: "0.2",
    ans: 1,
  },
  {
    que: "A shopkeeper marks his goods at 20% above the cost price and allows a discount of 10% on the marked price. What is his profit percentage?",
    opt1: "8%",
    opt2: "10%",
    opt3: "12%",
    opt4: "15%",
    ans: 1,
  },
  {
    que: "If a:b = 3:4 and b:c = 2:5, what is a:c?",
    opt1: "3:5",
    opt2: "3:10",
    opt3: "6:5",
    opt4: "5:6",
    ans: 2,
  },
  {
    que: "A person travels 3/8 of a journey by train, 1/4 by car, and the remaining 150 km by bus. What is the total distance of the journey?",
    opt1: "480 km",
    opt2: "600 km",
    opt3: "800 km",
    opt4: "750 km",
    ans: 2,
  },
  {
    que: "If the perimeter of a rectangle is 36 cm and its length is 10 cm, what is its area?",
    opt1: "80 cm²",
    opt2: "90 cm²",
    opt3: "100 cm²",
    opt4: "120 cm²",
    ans: 2,
  },
];

const computerScienceQuiz = [
  {
    que: "Which of the following sorting algorithms has the worst-case time complexity of O(n log n)?",
    opt1: "Quick Sort",
    opt2: "Merge Sort",
    opt3: "Heap Sort",
    opt4: "Bubble Sort",
    ans: 2,
  },
  {
    que: "In the context of databases, what does ACID stand for?",
    opt1: "Atomicity, Consistency, Isolation, Durability",
    opt2: "Automation, Control, Integrity, Durability",
    opt3: "Atomicity, Consistency, Integration, Durability",
    opt4: "Automation, Consistency, Isolation, Dependability",
    ans: 1,
  },
  {
    que: "Which of the following is NOT a characteristic of object-oriented programming?",
    opt1: "Encapsulation",
    opt2: "Inheritance",
    opt3: "Polymorphism",
    opt4: "Compilation",
    ans: 4,
  },
  {
    que: "In computer networks, which protocol is used for secure communication over a computer network?",
    opt1: "HTTP",
    opt2: "FTP",
    opt3: "HTTPS",
    opt4: "SMTP",
    ans: 3,
  },
  {
    que: "Which of the following is a NoSQL database?",
    opt1: "MySQL",
    opt2: "MongoDB",
    opt3: "PostgreSQL",
    opt4: "SQLite",
    ans: 2,
  },
  {
    que: "What is the main function of the CPU's ALU?",
    opt1: "Store data",
    opt2: "Perform arithmetic and logic operations",
    opt3: "Control input and output operations",
    opt4: "Manage memory",
    ans: 2,
  },
  {
    que: "Which of the following best describes a linked list?",
    opt1: "A data structure where each element points to the next",
    opt2: "A collection of elements stored at contiguous memory locations",
    opt3: "A data structure that follows the Last In First Out principle",
    opt4: "A collection of elements with a fixed size",
    ans: 1,
  },
  {
    que: "In operating systems, what is a 'deadlock'?",
    opt1: "A situation where two or more processes are unable to proceed because each is waiting for the other to release resources",
    opt2: "A type of virus that locks user files",
    opt3: "A situation where a program enters an infinite loop",
    opt4: "A security mechanism to prevent unauthorized access",
    ans: 1,
  },
  {
    que: "Which of the following is a characteristic of the C programming language?",
    opt1: "It is an object-oriented language",
    opt2: "It is a high-level assembly language",
    opt3: "It supports both high-level and low-level programming",
    opt4: "It does not support pointer arithmetic",
    ans: 3,
  },
  {
    que: "What does 'DNS' stand for in networking?",
    opt1: "Domain Name System",
    opt2: "Data Network Service",
    opt3: "Dynamic Naming System",
    opt4: "Digital Network Security",
    ans: 1,
  },
];

const dataScienceQuiz = [
  {
    que: "Which of the following is NOT a supervised learning algorithm?",
    opt1: "Decision Tree",
    opt2: "K-Means Clustering",
    opt3: "Support Vector Machine",
    opt4: "Random Forest",
    ans: 2,
  },
  {
    que: "What is the main advantage of using Principal Component Analysis (PCA) in data science?",
    opt1: "Increases dataset dimensionality",
    opt2: "Reduces overfitting by removing correlated features",
    opt3: "Improves training speed by normalizing data",
    opt4: "Makes categorical data more interpretable",
    ans: 2,
  },
  {
    que: "Which evaluation metric is commonly used for imbalanced classification problems?",
    opt1: "Accuracy",
    opt2: "Mean Squared Error",
    opt3: "F1-Score",
    opt4: "R-Squared",
    ans: 3,
  },
  {
    que: "In neural networks, what is the vanishing gradient problem?",
    opt1: "A situation where gradients become too large, leading to unstable training",
    opt2: "Gradients become too small, making it difficult for deep networks to learn",
    opt3: "A sudden drop in accuracy after several epochs",
    opt4: "A network failure due to poor data normalization",
    ans: 2,
  },
  {
    que: "Which of the following is NOT an activation function used in neural networks?",
    opt1: "ReLU",
    opt2: "Sigmoid",
    opt3: "Softmax",
    opt4: "Fourier Transform",
    ans: 4,
  },
  {
    que: "Which technique is commonly used for handling missing data in machine learning?",
    opt1: "Principal Component Analysis",
    opt2: "Mean or Median Imputation",
    opt3: "Gradient Boosting",
    opt4: "One-Hot Encoding",
    ans: 2,
  },
  {
    que: "In regression analysis, what is multicollinearity?",
    opt1: "When independent variables are highly correlated with each other",
    opt2: "When the dependent variable has a linear relationship with only one independent variable",
    opt3: "When a model has too many independent variables",
    opt4: "When training data is highly imbalanced",
    ans: 1,
  },
  {
    que: "Which type of machine learning algorithm is used for anomaly detection?",
    opt1: "Supervised Learning",
    opt2: "Unsupervised Learning",
    opt3: "Reinforcement Learning",
    opt4: "Genetic Algorithms",
    ans: 2,
  },
  {
    que: "What is a hyperparameter in machine learning?",
    opt1: "A parameter learned from the data during training",
    opt2: "A parameter manually set before training begins",
    opt3: "A variable that determines the accuracy of the model",
    opt4: "A randomly initialized parameter",
    ans: 2,
  },
  {
    que: "Which of the following is an ensemble learning technique?",
    opt1: "Random Forest",
    opt2: "K-Nearest Neighbors",
    opt3: "Gradient Descent",
    opt4: "Linear Regression",
    ans: 1,
  },
];

const engineeringCoreSciencesQuiz = [
  {
    que: "Which law states that the sum of voltages around a closed loop in a circuit is equal to zero?",
    opt1: "Ohm’s Law",
    opt2: "Kirchhoff’s Voltage Law",
    opt3: "Faraday’s Law",
    opt4: "Lenz’s Law",
    ans: 2,
  },
  {
    que: "In thermodynamics, what does the second law state about entropy?",
    opt1: "Entropy always decreases in a closed system",
    opt2: "Entropy remains constant in an isolated system",
    opt3: "Entropy always increases in an isolated system",
    opt4: "Entropy has no effect on a closed system",
    ans: 3,
  },
  {
    que: "What is the primary function of a flywheel in an engine?",
    opt1: "To store rotational energy and maintain constant angular velocity",
    opt2: "To increase torque output",
    opt3: "To regulate fuel consumption",
    opt4: "To cool the engine",
    ans: 1,
  },
  {
    que: "Which type of stress occurs in a material when it is subjected to opposing forces that are not aligned?",
    opt1: "Tensile stress",
    opt2: "Compressive stress",
    opt3: "Shear stress",
    opt4: "Bending stress",
    ans: 3,
  },
  {
    que: "In fluid mechanics, what is the primary assumption of Bernoulli’s theorem?",
    opt1: "Fluid flow is compressible and viscous",
    opt2: "Flow is steady, incompressible, and inviscid",
    opt3: "Fluid density varies with velocity",
    opt4: "Flow occurs in a turbulent regime",
    ans: 2,
  },
  {
    que: "What is the unit of thermal conductivity?",
    opt1: "W/mK",
    opt2: "J/m²K",
    opt3: "N/m²",
    opt4: "J/kgK",
    ans: 1,
  },
  {
    que: "Which of the following materials has the highest electrical conductivity?",
    opt1: "Copper",
    opt2: "Gold",
    opt3: "Aluminum",
    opt4: "Silver",
    ans: 4,
  },
  {
    que: "The Reynolds number is used to determine which characteristic of fluid flow?",
    opt1: "Temperature variation",
    opt2: "Flow velocity",
    opt3: "Laminar or turbulent nature of flow",
    opt4: "Pressure loss",
    ans: 3,
  },
  {
    que: "What is the primary advantage of using a transistor over a vacuum tube?",
    opt1: "Lower power consumption and size",
    opt2: "Higher resistance",
    opt3: "Greater power dissipation",
    opt4: "Better heat generation",
    ans: 1,
  },
  {
    que: "Which of the following types of bridges is the strongest in terms of load-bearing capacity?",
    opt1: "Suspension bridge",
    opt2: "Beam bridge",
    opt3: "Arch bridge",
    opt4: "Cable-stayed bridge",
    ans: 3,
  },
];

const businessManagementQuiz = [
  {
    que: "Which financial statement provides a snapshot of a company’s financial position at a specific time?",
    opt1: "Income Statement",
    opt2: "Balance Sheet",
    opt3: "Cash Flow Statement",
    opt4: "Profit & Loss Statement",
    ans: 2,
  },
  {
    que: "What does the term ‘Blue Ocean Strategy’ refer to in business?",
    opt1: "Competing in saturated markets",
    opt2: "Creating an uncontested market space",
    opt3: "Maximizing supply chain efficiency",
    opt4: "Reducing operational costs",
    ans: 2,
  },
  {
    que: "In marketing, what is the 80/20 rule (Pareto Principle) often used for?",
    opt1: "Identifying the most valuable customers",
    opt2: "Determining pricing strategies",
    opt3: "Predicting market trends",
    opt4: "Setting annual revenue targets",
    ans: 1,
  },
  {
    que: "Which leadership style involves giving employees full autonomy and decision-making power?",
    opt1: "Autocratic",
    opt2: "Democratic",
    opt3: "Laissez-faire",
    opt4: "Transformational",
    ans: 3,
  },
  {
    que: "What is ‘Net Present Value’ (NPV) used for in business?",
    opt1: "Measuring the total revenue of a project",
    opt2: "Assessing the profitability of an investment",
    opt3: "Calculating annual tax deductions",
    opt4: "Determining production costs",
    ans: 2,
  },
  {
    que: "Which pricing strategy involves initially setting a high price and then gradually lowering it?",
    opt1: "Penetration pricing",
    opt2: "Price skimming",
    opt3: "Value-based pricing",
    opt4: "Competitive pricing",
    ans: 2,
  },
  {
    que: "What does ‘SWOT’ analysis stand for in business strategy?",
    opt1: "Strategic Work Optimization Theory",
    opt2: "Strengths, Weaknesses, Opportunities, Threats",
    opt3: "Sales, Wages, Operations, Technology",
    opt4: "Systematic Workplace Organizational Tools",
    ans: 2,
  },
  {
    que: "What is the primary goal of Six Sigma in business management?",
    opt1: "Reducing production time",
    opt2: "Improving product design",
    opt3: "Minimizing defects and process variation",
    opt4: "Enhancing marketing reach",
    ans: 3,
  },
  {
    que: "Which of the following is an example of ‘Fixed Cost’ in business?",
    opt1: "Raw materials",
    opt2: "Employee wages",
    opt3: "Monthly office rent",
    opt4: "Utility bills",
    ans: 3,
  },
  {
    que: "Which inventory management system follows the principle of 'Just-In-Time' (JIT)?",
    opt1: "Producing goods in bulk for future sales",
    opt2: "Maintaining a high level of stock at all times",
    opt3: "Ordering raw materials only when needed",
    opt4: "Stockpiling products to meet uncertain demand",
    ans: 3,
  },
];

const medicalLifeSciencesQuiz = [
  {
    que: "Which organ is responsible for filtering waste from the blood?",
    opt1: "Liver",
    opt2: "Kidneys",
    opt3: "Pancreas",
    opt4: "Lungs",
    ans: 2,
  },
  {
    que: "What is the primary function of hemoglobin in red blood cells?",
    opt1: "Carrying oxygen",
    opt2: "Producing energy",
    opt3: "Digesting food",
    opt4: "Regulating blood pressure",
    ans: 1,
  },
  {
    que: "Which type of immunity is acquired through vaccination?",
    opt1: "Innate immunity",
    opt2: "Active acquired immunity",
    opt3: "Passive immunity",
    opt4: "Autoimmune response",
    ans: 2,
  },
  {
    que: "What is the term for the study of tissues?",
    opt1: "Cytology",
    opt2: "Pathology",
    opt3: "Histology",
    opt4: "Virology",
    ans: 3,
  },
  {
    que: "Which hormone is primarily responsible for regulating blood sugar levels?",
    opt1: "Adrenaline",
    opt2: "Insulin",
    opt3: "Estrogen",
    opt4: "Cortisol",
    ans: 2,
  },
  {
    que: "Which part of the brain controls balance and coordination?",
    opt1: "Cerebrum",
    opt2: "Medulla Oblongata",
    opt3: "Cerebellum",
    opt4: "Thalamus",
    ans: 3,
  },
  {
    que: "Which disease is caused by the deficiency of Vitamin C?",
    opt1: "Rickets",
    opt2: "Scurvy",
    opt3: "Beriberi",
    opt4: "Pellagra",
    ans: 2,
  },
  {
    que: "What is the medical term for high blood pressure?",
    opt1: "Hypotension",
    opt2: "Hypertension",
    opt3: "Hyperglycemia",
    opt4: "Hypoglycemia",
    ans: 2,
  },
  {
    que: "Which of the following is a bacterial disease?",
    opt1: "Influenza",
    opt2: "Tuberculosis",
    opt3: "Measles",
    opt4: "Hepatitis B",
    ans: 2,
  },
  {
    que: "Which organ produces bile, which aids in digestion?",
    opt1: "Pancreas",
    opt2: "Stomach",
    opt3: "Liver",
    opt4: "Gallbladder",
    ans: 3,
  },
];

const designCreativityQuiz = [
  {
    que: "What is the primary color model used in digital design?",
    opt1: "CMYK",
    opt2: "RGB",
    opt3: "Pantone",
    opt4: "HSL",
    ans: 2,
  },
  {
    que: "Which principle of design refers to the visual weight distribution in a composition?",
    opt1: "Contrast",
    opt2: "Balance",
    opt3: "Alignment",
    opt4: "Repetition",
    ans: 2,
  },
  {
    que: "Which file format is best for maintaining image quality in vector graphics?",
    opt1: "JPEG",
    opt2: "PNG",
    opt3: "SVG",
    opt4: "GIF",
    ans: 3,
  },
  {
    que: "Which type of typography has small decorative strokes at the ends of characters?",
    opt1: "Sans-serif",
    opt2: "Serif",
    opt3: "Script",
    opt4: "Monospace",
    ans: 2,
  },
  {
    que: "What does ‘UX’ stand for in design?",
    opt1: "User Xperience",
    opt2: "User Execution",
    opt3: "Unified Experience",
    opt4: "User Experience",
    ans: 4,
  },
  {
    que: "Which of the following design movements is characterized by bold colors and geometric shapes?",
    opt1: "Minimalism",
    opt2: "Bauhaus",
    opt3: "Art Deco",
    opt4: "Baroque",
    ans: 3,
  },
  {
    que: "What is the 'Golden Ratio' commonly used for in design?",
    opt1: "Calculating material costs",
    opt2: "Balancing proportions aesthetically",
    opt3: "Determining color schemes",
    opt4: "Scaling typography",
    ans: 2,
  },
  {
    que: "In color theory, what is the term for colors that are directly opposite each other on the color wheel?",
    opt1: "Analogous",
    opt2: "Complementary",
    opt3: "Monochromatic",
    opt4: "Triadic",
    ans: 2,
  },
  {
    que: "Which file format is best for printing high-quality graphics?",
    opt1: "JPEG",
    opt2: "PNG",
    opt3: "TIFF",
    opt4: "GIF",
    ans: 3,
  },
  {
    que: "What principle in UX design emphasizes making user actions reversible?",
    opt1: "Error prevention",
    opt2: "Affordance",
    opt3: "Flexibility",
    opt4: "Undo/Redo",
    ans: 4,
  },
];

const educationTeachingQuiz = [
  {
    que: "Which learning theory emphasizes that knowledge is actively constructed by the learner?",
    opt1: "Behaviorism",
    opt2: "Constructivism",
    opt3: "Cognitivism",
    opt4: "Humanism",
    ans: 2,
  },
  {
    que: "Who is known as the father of modern education?",
    opt1: "John Dewey",
    opt2: "Jean Piaget",
    opt3: "Maria Montessori",
    opt4: "Horace Mann",
    ans: 4,
  },
  {
    que: "What is Bloom’s Taxonomy used for?",
    opt1: "Evaluating teacher performance",
    opt2: "Classifying levels of learning",
    opt3: "Determining classroom seating arrangements",
    opt4: "Setting school policies",
    ans: 2,
  },
  {
    que: "Which of these is a student-centered teaching method?",
    opt1: "Lecture-based learning",
    opt2: "Project-based learning",
    opt3: "Drill and practice",
    opt4: "Direct instruction",
    ans: 2,
  },
  {
    que: "What is the primary goal of formative assessment?",
    opt1: "Assigning final grades",
    opt2: "Measuring long-term retention",
    opt3: "Providing feedback to improve learning",
    opt4: "Ranking students",
    ans: 3,
  },
  {
    que: "Which of the following is an example of a summative assessment?",
    opt1: "Quiz",
    opt2: "Final exam",
    opt3: "Class discussion",
    opt4: "Homework assignment",
    ans: 2,
  },
  {
    que: "What is differentiated instruction?",
    opt1: "Teaching all students the same way",
    opt2: "Adapting teaching methods to different learning styles",
    opt3: "Focusing only on gifted students",
    opt4: "Using only technology-based learning",
    ans: 2,
  },
  {
    que: "Which of the following is NOT a major learning style?",
    opt1: "Visual",
    opt2: "Auditory",
    opt3: "Tactile",
    opt4: "Comprehensive",
    ans: 4,
  },
  {
    que: "Who developed the theory of multiple intelligences?",
    opt1: "B.F. Skinner",
    opt2: "Howard Gardner",
    opt3: "John Dewey",
    opt4: "Jean Piaget",
    ans: 2,
  },
  {
    que: "What is the primary benefit of active learning?",
    opt1: "Students receive more homework",
    opt2: "Increases passive engagement",
    opt3: "Encourages participation and critical thinking",
    opt4: "Eliminates assessments",
    ans: 3,
  },
];

const governmentPublicServicesQuiz = [
  {
    que: "Which organization is responsible for maintaining international peace and security?",
    opt1: "World Trade Organization",
    opt2: "United Nations",
    opt3: "International Monetary Fund",
    opt4: "World Bank",
    ans: 2,
  },
  {
    que: "What does GDP stand for in economic policy?",
    opt1: "Gross Domestic Policy",
    opt2: "General Development Plan",
    opt3: "Gross Domestic Product",
    opt4: "Global Development Program",
    ans: 3,
  },
  {
    que: "Which branch of government is responsible for interpreting laws?",
    opt1: "Executive",
    opt2: "Legislative",
    opt3: "Judicial",
    opt4: "Administrative",
    ans: 3,
  },
  {
    que: "Which voting system is most commonly used in democratic elections?",
    opt1: "First-past-the-post",
    opt2: "Ranked-choice voting",
    opt3: "Proportional representation",
    opt4: "Sortition",
    ans: 1,
  },
  {
    que: "Which document outlines the fundamental rights of citizens in a country?",
    opt1: "Legislation Act",
    opt2: "Bill of Rights",
    opt3: "Electoral Manifesto",
    opt4: "Government Gazette",
    ans: 2,
  },
  {
    que: "Which of the following is NOT a function of the executive branch?",
    opt1: "Enforcing laws",
    opt2: "Making laws",
    opt3: "Signing executive orders",
    opt4: "Conducting foreign policy",
    ans: 2,
  },
  {
    que: "What is the primary purpose of a constitution?",
    opt1: "To outline citizens' rights and government structure",
    opt2: "To dictate military strategies",
    opt3: "To regulate businesses",
    opt4: "To determine international trade agreements",
    ans: 1,
  },
  {
    que: "Which form of government allows citizens to directly vote on laws?",
    opt1: "Representative democracy",
    opt2: "Direct democracy",
    opt3: "Oligarchy",
    opt4: "Monarchy",
    ans: 2,
  },
  {
    que: "Which international organization focuses on economic development and poverty reduction?",
    opt1: "United Nations",
    opt2: "World Bank",
    opt3: "NATO",
    opt4: "International Red Cross",
    ans: 2,
  },
  {
    que: "Which document formally declared the independence of the United States?",
    opt1: "The Bill of Rights",
    opt2: "The Declaration of Independence",
    opt3: "The Emancipation Proclamation",
    opt4: "The Constitution",
    ans: 2,
  },
];

const humanitiesSocialSciencesQuiz = [
  {
    que: "Who is considered the father of modern sociology?",
    opt1: "Karl Marx",
    opt2: "Émile Durkheim",
    opt3: "Max Weber",
    opt4: "Auguste Comte",
    ans: 4,
  },
  {
    que: "What is the primary focus of anthropology?",
    opt1: "Political systems",
    opt2: "Cultural and human evolution",
    opt3: "Economic trends",
    opt4: "Government policies",
    ans: 2,
  },
  {
    que: "Which philosophy is based on the idea that reality is socially constructed?",
    opt1: "Realism",
    opt2: "Positivism",
    opt3: "Social constructivism",
    opt4: "Empiricism",
    ans: 3,
  },
  {
    que: "Which ancient civilization is credited with developing democracy?",
    opt1: "Roman Empire",
    opt2: "Ancient Greece",
    opt3: "Egyptian Civilization",
    opt4: "Chinese Dynasties",
    ans: 2,
  },
  {
    que: "What does ‘Ethnocentrism’ refer to?",
    opt1: "A global perspective on cultures",
    opt2: "The belief that one’s own culture is superior",
    opt3: "Cultural relativism",
    opt4: "Diversity inclusion",
    ans: 2,
  },
  {
    que: "Which philosopher is famous for the statement 'I think, therefore I am'?",
    opt1: "Plato",
    opt2: "Aristotle",
    opt3: "René Descartes",
    opt4: "Immanuel Kant",
    ans: 3,
  },
  {
    que: "What is the primary goal of sociology?",
    opt1: "To understand human behavior in a social context",
    opt2: "To analyze ancient civilizations",
    opt3: "To study individual psychology",
    opt4: "To research economic policies",
    ans: 1,
  },
  {
    que: "Which theory in anthropology suggests that cultural traits spread from one society to another?",
    opt1: "Functionalism",
    opt2: "Cultural diffusion",
    opt3: "Structuralism",
    opt4: "Symbolic interactionism",
    ans: 2,
  },
  {
    que: "What is the term for the study of moral principles and ethical behavior?",
    opt1: "Sociology",
    opt2: "Anthropology",
    opt3: "Philosophy",
    opt4: "Ethics",
    ans: 4,
  },
  {
    que: "Which field of study explores the relationship between language and culture?",
    opt1: "Linguistic anthropology",
    opt2: "Psychology",
    opt3: "Political science",
    opt4: "Economics",
    ans: 1,
  },
];


import { FaBrain, FaLaptopCode, FaChartLine, FaBusinessTime, FaCogs, FaHeartbeat, FaUniversity, FaPaintBrush, FaBalanceScale, FaFlask, FaChalkboardTeacher, FaLandmark, FaGlobe } from "react-icons/fa";

const quizCategories = [
    {
      title: "General Aptitude & Career Interest",
      description: "Assess your logical reasoning, numerical ability, and personality traits to find the right career path.",
      array: generalAptitudeQuiz,
      logo: <FaBrain />,
    },
    {
      title: "Computer Science & IT",
      description: "Test your knowledge in programming, data structures, networking, and databases for a tech career.",
      array: computerScienceQuiz,
      logo: <FaLaptopCode />,
    },
    {
      title: "Data Science & Analytics",
      description: "Evaluate your skills in data handling, machine learning, statistics, and SQL to explore data-driven careers.",
      array: dataScienceQuiz,
      logo: <FaChartLine />,
    },
    {
      title: "Business & Management",
      description: "Measure your business acumen, decision-making, marketing, finance, and entrepreneurship skills.",
      array: businessManagementQuiz,
      logo: <FaBusinessTime />,
    },
    {
      title: "Engineering & Core Fields",
      description: "Check your knowledge in mechanical, electrical, civil, and electronics engineering concepts.",
      array: engineeringCoreSciencesQuiz,
      logo: <FaCogs />,
    },
    {
      title: "Healthcare & Medicine",
      description: "Assess your understanding of human biology, medical ethics, anatomy, and pharmacy basics.",
      array: medicalLifeSciencesQuiz,
      logo: <FaHeartbeat />,
    },
    {
      title: "Finance & Accounting",
      description: "Test your grasp of accounting principles, investment strategies, taxation, and economics.",
      array: financeAccountingQuiz,
      logo: <FaUniversity />,
    },
    {
      title: "Media & Design",
      description: "Explore your creativity with questions on color theory, UI/UX, branding, and storytelling.",
      array: designCreativityQuiz,
      logo: <FaPaintBrush />,
    },
    {
      title: "Law & Public Administration",
      description: "Evaluate your knowledge of the Indian Constitution, legal reasoning, general awareness, and civics.",
      array: lawPublicAdministrationQuiz,
      logo: <FaBalanceScale />,
    },
    {
      title: "Science & Research",
      description: "Assess your understanding of scientific methods, experiments, innovations, and environmental science.",
      array: scienceResearchQuiz,
      logo: <FaFlask />,
    },
    {
      title: "Education & Teaching",
      description: "Test your knowledge of pedagogy, learning theories, classroom management, and modern educational technologies.",
      array: educationTeachingQuiz,
      logo: <FaChalkboardTeacher />,
    },
    {
      title: "Government & Public Services",
      description: "Evaluate your understanding of governance, public policy, civil services, and administrative functions in the public sector.",
      array: governmentPublicServicesQuiz,
      logo: <FaLandmark />,
    },
    {
      title: "Humanities & Social Sciences",
      description: "Dive into topics related to history, sociology, psychology, philosophy, and cultural studies to challenge your analytical thinking.",
      array: humanitiesSocialSciencesQuiz,
      logo: <FaGlobe />,
    },
];

export default quizCategories;
